name: build mosaic scala
description: build mosaic scala
inputs: 
  skip_tests:
    description: 'Skip Scala Tests? true or false'
    default: 'false'
runs:
  using: "composite"
  steps:
        - name: Configure JDK
          uses: actions/setup-java@v2
          with:
            java-version: '8'
            distribution: 'zulu'
        - name: Test and build the scala JAR - skip tests is false
          if: inputs.skip_tests == 'false'
          shell: bash
          run: |
            pip install databricks-mosaic-gdal==3.4.3
            sudo tar -xf /home/runner/.local/lib/python3.8/site-packages/databricks-mosaic-gdal/resources/gdal-3.4.3-filetree.tar.xz -C /
            sudo tar -xhf /home/runner/.local/lib/python3.8/site-packages/databricks-mosaic-gdal/resources/gdal-3.4.3-symlinks.tar.xz -C /
            sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable
            sudo apt clean && sudo apt -o Acquire::Retries=3 update --fix-missing -y
            sudo apt-get -o Acquire::Retries=3 update -y
            sudo apt-get -o Acquire::Retries=3 install -y gdal-bin=3.4.3+dfsg-1~focal0 libgdal-dev=3.4.3+dfsg-1~focal0 python3-gdal=3.4.3+dfsg-1~focal0
            sudo mvn -q clean install
        - name: Build the scala JAR - skip tests is true
          if: inputs.skip_tests == 'true'
          shell: bash
          run: sudo mvn -q clean install -DskipTests -Dscoverage.skip
        - name: Publish test coverage
          if: inputs.skip_tests == 'false'
          uses: codecov/codecov-action@v1
        - name: Copy Scala artifacts to GH Actions run
          shell: bash
          run: |
            mkdir staging
            cp target/mosaic*.jar staging
