name: build mosaic python
description: build mosaic python
runs:
  using: "composite"
  steps:
    - name: Configure python interpreter
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install python dependencies
      shell: bash
      run: |
        # - update apt
        sudo apt-add-repository "deb http://archive.ubuntu.com/ubuntu $(lsb_release -sc)-backports main universe multiverse restricted"
        sudo apt-add-repository "deb http://archive.ubuntu.com/ubuntu $(lsb_release -sc)-updates main universe multiverse restricted"
        sudo apt-add-repository "deb http://archive.ubuntu.com/ubuntu $(lsb_release -sc)-security main multiverse restricted universe"
        sudo apt-add-repository "deb http://archive.ubuntu.com/ubuntu $(lsb_release -sc) main multiverse restricted universe"
        sudo apt-get update -y
        # - install natives
        sudo apt-get install -y unixodbc libcurl3-gnutls libsnappy-dev libopenjp2-7
        sudo apt-get install -y gdal-bin libgdal-dev python3-numpy python3-gdal
        # - install pip libs
        cd python
        pip install --upgrade pip
        pip install gdal==${{ matrix.gdal }}
        pip install build wheel pyspark==${{ matrix.spark }} 
        pip install .
    - name: Test and build python package
      shell: bash
      run: |
        cd python
        python -m unittest
        python -m build
    - name: Copy python artifacts to GH Actions run
      shell: bash
      run: cp python/dist/*.whl staging