name: build mosaic python
description: build mosaic python
runs:
  using: "composite"
  steps:
    - name: Configure python interpreter
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install python dependencies
      shell: bash
      run: |
        cd python
        sudo pip install build wheel pyspark==${{ matrix.spark }}
        sudo pip install .
    - name: Test and build python package
      shell: bash
      run: |
        cd python
        sudo python -m unittest
        sudo python -m build
    - name: Copy python artifacts to GH Actions run
      shell: bash
      run: cp python/dist/*.whl staging