name: Build mosaic project
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'
jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python: [3.8.10]
        spark: [3.2.1]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Configure JDK
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'zulu'
    - name: Test and build the scala JAR
      run: mvn -q clean install
    - name: Configure python interpreter
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install python dependencies
      run: |
        cd python
        pip install build wheel pyspark==${{ matrix.spark }}
        pip install .
    - name: Test and build python package
      run: |
        cd python 
        python -m unittest
        python -m build
    - name: Copy python artifacts to GH Actions run
      run: cp python/dist/*.whl staging
    - uses: actions/upload-artifact@v2
      with:
        name: artefacts
        path: staging
